# Generated by Django 3.1.4 on 2020-12-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user/avatar', verbose_name='avatar'),
        ),
    ]
