# Generated by Django 3.0.5 on 2020-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200411_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headertitle',
            name='title',
            field=models.CharField(max_length=70, verbose_name='title'),
        ),
    ]
