# Generated by Django 3.0.6 on 2020-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200411_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('body', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title1', models.CharField(max_length=70, null=True, verbose_name='main_title1')),
                ('main_title2', models.CharField(max_length=70, null=True, verbose_name='main_title2')),
                ('main_text1', models.CharField(max_length=1000, null=True, verbose_name='main_text1')),
                ('about_us_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about_us_text', models.CharField(max_length=1500, null=True, verbose_name='about_us_text')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='HeaderTitle',
        ),
    ]
