# Generated by Django 3.0.5 on 2020-04-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fiutartitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiutartitle',
            name='fiutartitle1',
        ),
        migrations.AddField(
            model_name='fiutartitle',
            name='title2',
            field=models.CharField(default=1, max_length=70, verbose_name='title2'),
            preserve_default=False,
        ),
    ]
