# Generated by Django 3.0.5 on 2020-04-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_aboutustext_aboutustitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsTitle',
        ),
    ]
