# Generated by Django 3.0.6 on 2020-05-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_aboutustitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title1', models.CharField(max_length=70, null=True, verbose_name='main_title1')),
                ('main_title2', models.CharField(max_length=70, null=True, verbose_name='main_title2')),
                ('main_text1', models.CharField(max_length=1000, null=True, verbose_name='main_text1')),
                ('about_us_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='about_us_image')),
                ('about_us_text', models.CharField(max_length=1500, null=True, verbose_name='about_us_text')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUsText',
        ),
        migrations.DeleteModel(
            name='FiutarText',
        ),
        migrations.DeleteModel(
            name='FiutarTitle',
        ),
        migrations.DeleteModel(
            name='HeaderTitle',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
