# Generated by Django 3.0.6 on 2020-05-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200512_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home_detail',
            new_name='HomeDetail',
        ),
    ]
