# Generated by Django 3.0.6 on 2020-05-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200512_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetail',
            name='about_us_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
