# Generated by Django 3.0.6 on 2020-05-13 15:18

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200513_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetail',
            name='about_us_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=home.models.path_and_rename),
        ),
    ]
