# Generated by Django 3.0.6 on 2020-05-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200514_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='body',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
