# Generated by Django 3.0.6 on 2020-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200514_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='body',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
