# Generated by Django 3.0.6 on 2020-05-14 10:02

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200514_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=home.models.get_image_filename),
        ),
    ]
