# Generated by Django 3.1.4 on 2021-01-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='post/images', verbose_name='Image'),
        ),
    ]
