# Generated by Django 3.1.4 on 2020-12-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201219_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_title',
            field=models.ImageField(blank=True, upload_to='images/title', verbose_name='image title'),
        ),
    ]
