# Generated by Django 3.1.4 on 2020-12-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201220_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(db_index=True, default=True, verbose_name='draft'),
        ),
    ]
